# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    mappings:
        image_admin:
            uri_prefix: /assets/img/admin
            upload_destination: '%kernel.project_dir%/public/assets/img/admin'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        image_consultants:
            uri_prefix: /assets/img/consultants
            upload_destination: '%kernel.project_dir%/public/assets/img/consultants'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true